In [15]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [16]:
df = pd.read_csv('datasets/test_14.csv')

In [17]:
oe = OrdinalEncoder()
oe.fit(df[['Eğitim Durumu']])

OrdinalEncoder()

In [18]:
transformed_data = oe.transform(df[['Eğitim Durumu']])
print(transformed_data)

[[0.]
 [0.]
 [3.]
 [1.]
 [0.]
 [2.]
 [3.]]


In [19]:
df['Eğitim Durumu'] = oe.transform(df[['Eğitim Durumu']])
df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet Renk Tercihi  Eğitim Durumu
0  Sacit Bulut    78  172   34    Erkek      Kırmızı            0.0
1      Ayşe Er    67  168   45    Kadın        Yeşil            0.0
2    Ahmet San    85  182   32    Erkek      Kırmızı            3.0
3    Macit Şen    98  192   65    Erkek         Mavi            1.0
4  Talat Demir    85  181   49    Erkek        Yeşil            0.0
5   Sibel Ünlü    72  172   34    Kadın         Mavi            2.0
6    Ali Serçe    75  165   21    Erkek        Yeşil            3.0

In [20]:
oe.inverse_transform(df[['Eğitim Durumu']])

array([['Lisans'],
       ['Lisans'],
       ['İlkokul'],
       ['Ortaokul'],
       ['Lisans'],
       ['Yüksek Lisans'],
       ['İlkokul']], dtype=object)

### ONE HOT ENCODING


In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('datasets/test_14.csv')
df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet Renk Tercihi  Eğitim Durumu
0  Sacit Bulut    78  172   34    Erkek      Kırmızı         Lisans
1      Ayşe Er    67  168   45    Kadın        Yeşil         Lisans
2    Ahmet San    85  182   32    Erkek      Kırmızı        İlkokul
3    Macit Şen    98  192   65    Erkek         Mavi       Ortaokul
4  Talat Demir    85  181   49    Erkek        Yeşil         Lisans
5   Sibel Ünlü    72  172   34    Kadın         Mavi  Yüksek Lisans
6    Ali Serçe    75  165   21    Erkek        Yeşil        İlkokul

In [3]:
ohe = OneHotEncoder(sparse_output=False)

In [4]:
ohe.fit(df[['Renk Tercihi']])

OneHotEncoder(sparse_output=False)

In [5]:
ohe_data = ohe.transform(df[['Renk Tercihi']])
print(ohe_data)

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
df.drop('Renk Tercihi', axis=1, inplace=True) 
df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Eğitim Durumu
0  Sacit Bulut    78  172   34    Erkek         Lisans
1      Ayşe Er    67  168   45    Kadın         Lisans
2    Ahmet San    85  182   32    Erkek        İlkokul
3    Macit Şen    98  192   65    Erkek       Ortaokul
4  Talat Demir    85  181   49    Erkek         Lisans
5   Sibel Ünlü    72  172   34    Kadın  Yüksek Lisans
6    Ali Serçe    75  165   21    Erkek        İlkokul

In [28]:
df[['Kırmızı', 'Mavi', 'Yeşil']] = ohe_data
df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Eğitim Durumu  Kırmızı  Mavi  Yeşil
0  Sacit Bulut    78  172   34    Erkek         Lisans      1.0   0.0    0.0
1      Ayşe Er    67  168   45    Kadın         Lisans      0.0   0.0    1.0
2    Ahmet San    85  182   32    Erkek        İlkokul      1.0   0.0    0.0
3    Macit Şen    98  192   65    Erkek       Ortaokul      0.0   1.0    0.0
4  Talat Demir    85  181   49    Erkek         Lisans      0.0   0.0    1.0
5   Sibel Ünlü    72  172   34    Kadın  Yüksek Lisans      0.0   1.0    0.0
6    Ali Serçe    75  165   21    Erkek        İlkokul      0.0   0.0    1.0

In [ ]:
# import numpy as np

# cats = np.unique(df['Renk Tercihi'].to_list()) 
# df.drop('Renk Tercihi', axis=1, inplace=True)
# df[cats] = ohe_data
# df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet Renk Tercihi  Eğitim Durumu  Kırmızı  \
0  Sacit Bulut    78  172   34    Erkek      Kırmızı         Lisans      1.0   
1      Ayşe Er    67  168   45    Kadın        Yeşil         Lisans      0.0   
2    Ahmet San    85  182   32    Erkek      Kırmızı        İlkokul      1.0   
3    Macit Şen    98  192   65    Erkek         Mavi       Ortaokul      0.0   
4  Talat Demir    85  181   49    Erkek        Yeşil         Lisans      0.0   
5   Sibel Ünlü    72  172   34    Kadın         Mavi  Yüksek Lisans      0.0   
6    Ali Serçe    75  165   21    Erkek        Yeşil        İlkokul      0.0   

   Mavi  Yeşil  
0   0.0    0.0  
1   0.0    1.0  
2   0.0    0.0  
3   1.0    0.0  
4   0.0    1.0  
5   1.0    0.0  
6   0.0    1.0

In [ ]:
# ohe.fit(df[['Renk Tercihi', 'Meslek']])
# ohe_data = ohe.transform(df[['Renk Tercihi', 'Meslek']])
# print(ohe_data, end='\n\n')

# df.drop('Renk Tercihi', axis=1, inplace=True)
# df.drop('Meslek', axis=1, inplace=True)

# df[ohe.categories_[0]] = ohe_data[:, :3]
# df[ohe.categories_[1]] = ohe_data[:, 3:]

# print(df, end='\n\n')

### ONE HOT ENCODING WITH PANDAS - NEW METHOD


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('datasets/test_14.csv')
df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet Renk Tercihi  Eğitim Durumu    Meslek
0  Sacit Bulut    78  172   34    Erkek      Kırmızı         Lisans  Mühendis
1      Ayşe Er    67  168   45    Kadın        Yeşil         Lisans    Doktor
2    Ahmet San    85  182   32    Erkek      Kırmızı        İlkokul  Öğretmen
3    Macit Şen    98  192   65    Erkek         Mavi       Ortaokul  Mühendis
4  Talat Demir    85  181   49    Erkek        Yeşil         Lisans  Öğretmen
5   Sibel Ünlü    72  172   34    Kadın         Mavi  Yüksek Lisans  Mühendis
6    Ali Serçe    75  165   21    Erkek        Yeşil        İlkokul    Doktor

### ONE HOT ENCODING With Pandas Method


In [ ]:
# ohe_df = pd.get_dummies(df, columns=['Renk Tercihi', 'Meslek'])
# ohe_df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Eğitim Durumu  Renk Tercihi_Kırmızı  \
0  Sacit Bulut    78  172   34    Erkek         Lisans                  True   
1      Ayşe Er    67  168   45    Kadın         Lisans                 False   
2    Ahmet San    85  182   32    Erkek        İlkokul                  True   
3    Macit Şen    98  192   65    Erkek       Ortaokul                 False   
4  Talat Demir    85  181   49    Erkek         Lisans                 False   
5   Sibel Ünlü    72  172   34    Kadın  Yüksek Lisans                 False   
6    Ali Serçe    75  165   21    Erkek        İlkokul                 False   

   Renk Tercihi_Mavi  Renk Tercihi_Yeşil  Meslek_Doktor  Meslek_Mühendis  \
0              False               False          False             True   
1              False                True           True            False   
2              False               False          False            False   
3               True               False          False             True   
4              False                True          False            False   
5               True               False          False             True   
6              False                True           True            False   

   Meslek_Öğretmen  
0            False  
1            False  
2             True  
3            False  
4             True  
5            False  
6            False

### ONE HOT ENCODING With Keras Method

In [14]:
import numpy as np

color_cats = np.unique(df['Renk Tercihi'].to_numpy())
occupation_cats = np.unique(df['Meslek'].to_numpy())

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Renk Tercihi"] = le.fit_transform(df['Renk Tercihi'])
df["Meslek"] = le.fit_transform(df['Meslek'])

df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Renk Tercihi  Eğitim Durumu  Meslek
0  Sacit Bulut    78  172   34    Erkek             0         Lisans       1
1      Ayşe Er    67  168   45    Kadın             2         Lisans       0
2    Ahmet San    85  182   32    Erkek             0        İlkokul       2
3    Macit Şen    98  192   65    Erkek             1       Ortaokul       1
4  Talat Demir    85  181   49    Erkek             2         Lisans       2
5   Sibel Ünlü    72  172   34    Kadın             1  Yüksek Lisans       1
6    Ali Serçe    75  165   21    Erkek             2        İlkokul       0

In [16]:
from tensorflow.keras.utils import to_categorical

In [17]:
ohe_color = to_categorical(df['Renk Tercihi'])
ohe_occupation = to_categorical(df['Meslek'])

In [18]:
df.drop('Renk Tercihi', axis=1, inplace=True)
df[color_cats] = ohe_color

In [ ]:
df.drop('Meslek', axis=1, inplace=True)
df[occupation_cats] = ohe_occupation

In [20]:
df

Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Eğitim Durumu  Kırmızı  Mavi  Yeşil  \
0  Sacit Bulut    78  172   34    Erkek         Lisans      1.0   0.0    0.0   
1      Ayşe Er    67  168   45    Kadın         Lisans      0.0   0.0    1.0   
2    Ahmet San    85  182   32    Erkek        İlkokul      1.0   0.0    0.0   
3    Macit Şen    98  192   65    Erkek       Ortaokul      0.0   1.0    0.0   
4  Talat Demir    85  181   49    Erkek         Lisans      0.0   0.0    1.0   
5   Sibel Ünlü    72  172   34    Kadın  Yüksek Lisans      0.0   1.0    0.0   
6    Ali Serçe    75  165   21    Erkek        İlkokul      0.0   0.0    1.0   

   Doktor  Mühendis  Öğretmen  
0     0.0       1.0       0.0  
1     1.0       0.0       0.0  
2     0.0       0.0       1.0  
3     0.0       1.0       0.0  
4     0.0       0.0       1.0  
5     0.0       1.0       0.0  
6     1.0       0.0       0.0

### ONE HOT ENCODING With Unit Matrix Method



In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('datasets/test_14.csv')

# print(df, end='\n\n')

color_cats = np.unique(df['Renk Tercihi'].to_numpy())
occupation_cats = np.unique(df['Meslek'].to_numpy())

le = LabelEncoder()
df['Renk Tercihi'] = le.fit_transform(df['Renk Tercihi'])
df['Meslek'] = le.fit_transform(df['Meslek'])

print(df, end='\n\n')

color_um = np.eye(len(color_cats))
occupation_um = np.eye(len(occupation_cats))

ohe_color = color_um[df['Renk Tercihi'].to_numpy()]
ohe_occupation = occupation_um[df['Meslek'].to_numpy()]

df.drop(['Renk Tercihi', 'Meslek'], axis=1, inplace=True)
df[color_cats] = ohe_color
df[occupation_cats] = ohe_occupation

print(df, end='\n\n')

    Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Renk Tercihi  Eğitim Durumu  Meslek
0  Sacit Bulut    78  172   34    Erkek             0         Lisans       1
1      Ayşe Er    67  168   45    Kadın             2         Lisans       0
2    Ahmet San    85  182   32    Erkek             0        İlkokul       2
3    Macit Şen    98  192   65    Erkek             1       Ortaokul       1
4  Talat Demir    85  181   49    Erkek             2         Lisans       2
5   Sibel Ünlü    72  172   34    Kadın             1  Yüksek Lisans       1
6    Ali Serçe    75  165   21    Erkek             2        İlkokul       0

    Adı Soyadı  Kilo  Boy  Yaş Cinsiyet  Eğitim Durumu  Kırmızı  Mavi  Yeşil  \
0  Sacit Bulut    78  172   34    Erkek         Lisans      1.0   0.0    0.0   
1      Ayşe Er    67  168   45    Kadın         Lisans      0.0   0.0    1.0   
2    Ahmet San    85  182   32    Erkek        İlkokul      1.0   0.0    0.0   
3    Macit Şen    98  192   65    Erkek       Ortaokul      0.0